### ISSUE TITLE
🟡  Rest API naming convention

### ISSUE THREAD

**Issue by CarlosCano93** [fjaviermelero/restapi#1]
There are some conventions about CRUD endpoint:

Action | Method | Name |
------ | ------ | ------ |
Create | POST | v1/authors |
Read | GET | v1/authors/{id} |
Read all | GET | v1/authors |
Update |  PUT | v1/authors |
Delete | DELETE | v1/authors/{id} |
Read 2lvl | GET | v1/authors/{id}/books/{id} |

More info [here](https://restfulapi.net/resource-naming/).

**Comment by fjaviermelero** [comment]
Level 2 read included in ProductionLineController in order to be able to find machines.

```
    @GetMapping("/productionlines/{idProdLine}/machines/{idMachine}")
    MachineDto getMachineFromProdLine(@PathVariable Long idProdLine, @PathVariable Long idMachine){

        MachineDto machineDto = machineService.findById(idMachine);

        if (!Objects.equals(machineDto.getProductionLineId(), idProdLine))
            throw new NotFoundException();

        return machineDto;
    }
```
